export enum Routes {
  // Define your routes here
  backendRoot = 'https://nussucommit-backend.herokuapp.com',
  index = '/',
  aboutUs = '/aboutus/overview',
  ourFamily = '/aboutus/our-family',
  visionMission = '/aboutus/vision-and-mission',
  ourStructure = '/aboutus/our-structure',
  managementCommittee = '/aboutus/management-committee',
  computerCentres = '/computer-centres',
  externalWorkshops = '/external-workshops',
  sdp = '/sdp',
  pdpa = '/pdpa',
  creation = '/events/creation',
  chariteach = '/events/chariteach',
  cyberia = '/events/cyberia',
  events = '/events',
  FAQ = '/FAQ',
  feedback = '/feedback',
  contact = '/contact',
  trainingWorkshops = '/training-workshops',
}
