export enum Routes {
  // Define your routes here
  backendRoot = "http://localhost:8000",
  index = '/',
  aboutUs = '/about-us',
  ourFamily = '/about-us/our-family',
  visionMission = '/about-us/vision-mission',
  ourStructure = '/about-us/our-structure',
  managementCommittee = '/about-us/management-committee',
  computerCentres = '/computer-centres',
  externalWorkshops = '/external-workshops',
  sdp = '/sdp',
  pdpa = '/pdpa',
  creation = '/events/creation',
  chariteach = '/events/chariteach',
  cyberia = '/events/cyberia',
  events = '/events',
  FAQ = '/FAQ',
  feedback = '/feedback',
  contact = '/contact',
  trainingWorkshops = '/training-workshops',
}
