//TODO: update content below, currently they are just placeholders.
export const directors = [
  {
    key: 1,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Co-Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/190/190811.png',
  },
  {
    key: 2,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Co-Director',
    faculty: 'Faculty of Arts & Social Science',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/190/190811.png',
  },
  {
    key: 3,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Co-Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/190/190811.png',
  },
]

export const comm = [
  {
    key: 4,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Secretary',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/1940/1940752.png',
  },
  {
    key: 5,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Secretary',
    faculty: 'Faculty of Arts & Social Science',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/1940/1940752.png',
  },
  {
    key: 6,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Treasurer',
    faculty: 'School of Computing',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/1907/1907938.png',
  },
  {
    key: 7,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Treasurer',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/1907/1907938.png',
  },
  {
    key: 8,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Ops & Logs Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/3139/3139209.png',
  },
  {
    key: 9,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Ops & Logs Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/3139/3139209.png',
  },
  {
    key: 10,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Marketing Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/7572/7572539.png',
  },
  {
    key: 11,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Marketing Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/7572/7572539.png',
  },
  {
    key: 12,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Publicity Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/2857/2857527.png',
  },
  {
    key: 13,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Publicity Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/2857/2857527.png',
  },
  {
    key: 14,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Technical Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/6062/6062646.png',
  },
  {
    key: 15,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Technical Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/6062/6062646.png',
  },
  {
    key: 16,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Training Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/3061/3061022.png',
  },
  {
    key: 17,
    name: 'John Doe',
    pic: 'https://dl.memuplay.com/new_market/img/com.vicman.newprofilepic.icon.2022-06-07-21-33-07.png',
    position: 'Training Director',
    faculty: 'College of Design & Engineering',
    year: 'Year 3',
    icon: 'https://cdn-icons-png.flaticon.com/512/3061/3061022.png',
  },
]
